homeassistant:
  name: Home
  latitude: !secret hass_lat
  longitude: !secret hass_long
  elevation: 6
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named yaml/customization
  packages: !include_dir_named yaml/packages

device_tracker: !include_dir_merge_list yaml/device_tracker
camera: !include_dir_merge_list yaml/camera
binary_sensor: !include_dir_merge_list yaml/binary_sensor
cover: !include_dir_merge_list yaml/cover
sensor: !include_dir_merge_list yaml/sensor
automation: !include_dir_merge_list yaml/automation
switch: !include_dir_merge_list yaml/switch
notify: !include_dir_merge_list yaml/notify
light: !include_dir_merge_list yaml/light
scene: !include_dir_merge_list yaml/scene
# proximity: !include_dir_list yaml/proximity
input_boolean: !include_dir_merge_named yaml/input_boolean
script: !include_dir_merge_named yaml/script
group: !include_dir_merge_named yaml/group

mqtt: !include yaml/mqtt.yaml
mysensors: !include yaml/mysensors.yaml
logger: !include yaml/logger.yaml
media_player: !include yaml/media_player.yaml
emulated_hue: !include yaml/emulated_hue.yaml
http: !include yaml/http.yaml
# zone: !include yaml/zones.yaml
shell_command: !include yaml/shell_commands.yaml

ifttt:
  key: !secret ifttt_key

tts:
 - platform: google
   cache: true
   cache_dir: /run/hass/tts
   time_memory: 300

#weather:
#  - platform: openweathermap
#    api_key: !secret openweathermap_api_key

sun:
updater:
# conversation:

# recorder: !include yaml/recorder.yaml
# history: !include yaml/history.yaml

# logbook:
# discovery:
zeroconf:

ios: !include yaml/ios.yaml
# ios:
#   push:
#     categories:
#       - name: Alarm
#         identifier: 'ALARM'
#         actions:
#           - identifier: 'SOUND_ALARM'
#             title: 'Sound Alarm'
#             activationMode: 'background'
#             authenticationRequired: yes
#             destructive: yes
#             behavior: 'default'
#           - identifier: 'SILENCE_ALARM'
#             title: 'Silence Alarm'
#             activationMode: 'background'
#             authenticationRequired: yes
#             destructive: no
#             behavior: 'default'
#             textInputButtonTitle: 'Silencio!'
#             textInputPlaceholder: 'Placeholder'



frontend:
