- alias: Garage Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.master_automation
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.garage_lights_motion
