# - alias: Garage Motion
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.garage_motion
#       to: 'on'
#   condition:
#     condition: state
#     entity_id: input_boolean.master_automation
#     state: 'on'
#   action:
#     service: homeassistant.turn_on
#     entity_id: script.garage_lights_motion

- alias: Home Arrival
  trigger:
    - platform: state
      entity_id: device_tracker.dwmi5,device_tracker.toyota_prius
      to: 'home'
  action:
    - service: notify.ios_dwmi5
      data:
        message: "Welcome home {{ trigger.to_state.attributes.friendly_name }}."
    - service: notify.pushbullet
      data:
        title: "Wecome Home"
        message: "Wecome Home {{ trigger.attributes.friendly_name }}."
    - service: homeassistant.turn_on
      entity_id: switch.slampher_173b67
    - delay: 00:10:00
    - service: homeassistant.turn_off
      entity_id: switch.slampher_173b67
