- alias: Kitchen Motion at night
  trigger:
    - platform: state
      entity_id: binary_sensor.node_21_22
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: time
        before: '07:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.kitchen_lights_motion
