- alias: Turn on christmas tree when motion in living room
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_51_20
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_christmas
