- alias: Lights at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.window_candles
      - group.porch_lights
      - switch.garage_light
      - switch.garage_light_pi

- alias: Lights off at 11pm
  trigger:
    platform: time
    hours: 23
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.window_candles
      - group.porch_lights
      - switch.garage_light
      - switch.garage_light_pi

