alias: Traffic to Rehoboth
trigger:
  platform: numeric_state
  entity_id: sensor.drive_to_rehoboth
  above: 30
conditions:
  - condition: state
    entity_id: device_tracker.dwmi5
    state: 'home'
action:
  service: notify.pushbullet
  data_template:
    message: >
      Traffic to Rehoboth. {{ trigger.to_state.state|round }} minutes.
