- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  origin: !secret google_travel_time_origin
  destination: !secret google_travel_time_destination_1
  name: !secret google_travel_time_name_1   
- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  origin: !secret google_travel_time_origin
  destination: !secret google_travel_time_destination_2
  name: !secret google_travel_time_name_2
- platform: google_travel_time
  name: Phone To Home
  api_key: !secret google_travel_time_api_key
  origin: device_tracker.owntracks_dwmi5
  destination: zone.home

