- platform: google_geocode
  name: geocode_dwmi5
  origin: device_tracker.dwmi5
  options: street_number, street, city, county, state
  display_zone: show
  api_key: !secret google_travel_time_api_key

- platform: google_geocode
  name: geocode_prius
  origin: device_tracker.toyota_prius
  options: street_number, street, city, county, state
  display_zone: show
  api_key: !secret google_travel_time_api_key

# https://github.com/michaelmcarthur/GoogleGeocode-HASS
