- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Current HA Version
- platform: command_line
  name: Installed HA Version
  command: "/srv/hass/bin/hass --version"

