- platform: template
  sensors:
      chromecast:
        friendly_name: 'ChromeCast'
        value_template: "{{ 'Online' if is_state('device_tracker.6cadf84f2951', 'home') else 'Offline' }}"
      engenius_ap:
        friendly_name: 'EnGenius AP'
        value_template: "{{ 'Online' if is_state('device_tracker.00026fa196b8', 'home') else 'Offline' }}"
      viostor_nvr:
        friendly_name: 'VioStor NVR'
        value_template: "{{ 'Online' if is_state('device_tracker.00089bcb17cc', 'home') else 'Offline' }}"
      sonicwall:
        friendly_name: 'SonicWall'
        value_template: "{{ 'Online' if is_state('device_tracker.0017c53ba4f0', 'home') else 'Offline' }}"
      airport_extreme:
        friendly_name: 'Airport Extreme'
        value_template: "{{ 'Online' if is_state('device_tracker.002436a06bb8', 'home') else 'Offline' }}"
      ecoplug_2:
        friendly_name: 'ecoPlug 2'
        value_template: "{{ 'Online' if is_state('device_tracker.382b7807780e', 'home') else 'Offline' }}"

