- platform: dht
  sensor: DHT11
  pin: 22
  monitored_conditions:
    - temperature
    - humidity

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'


- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_free
      arg: /mnt/media/
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
#     - type: since_last_boot

