automations:
  name: Automation Controls
  entities:
    - automation.motion_alarm_notification
    - automation.house_temperature_notification
    - automation.startup_notification
    - automation.livingroom_motion
    - automation.window_candles_sunset
    - automation.windows_candles_11pm
    - automation.kitchen_motion
    - automation.kitchen_button
    - automation.garage_motion
