environment:
  name: Environment
  view: yes
  icon: mdi:weather-partlycloudy
  entities:
#    - sun.sun
#    - sensor.sunrise
#    - sensor.sunset
#    - sensor.moon
    - group.astro
    - group.darksky
#    - group.openweathermap
    - group.wunderground
#    - weather.openweathermap
#    - group.yweather
    - group.local_weather
    - camera.animated_radar
