environment:
  name: Environment
  view: yes
  icon: mdi:weather-partlycloudy
  entities:
    - sun.sun
    - sensor.moon
    - group.darksky
    - group.openweathermap
    - group.wunderground
#    - weather.openweathermap
#    - group.yweather
