- platform: mqtt
  name: "living_room_lamp"
  state_topic: "/house/espurna/Living-Room-Lamp/relay/0/status"
  command_topic: "/house/espurna/Living-Room-Lamp/relay/0/set"
  payload_on: "1"
  payload_off: "0"
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: "christmas_tree_old"
  state_topic: "/house/espurna/Christmas-Tree/relay/0/status"
  command_topic: "/house/espurna/Christmas-Tree/relay/0/set"
  payload_on: "1"
  payload_off: "0"
  optimistic: false
  qos: 0
  retain: true
