- platform: nmap_tracker
  hosts: 192.168.9.1-255
  track_new_devices: no
  consider_home: 1800
  interval_seconds: 60
  home_interval: 5
  scan_options: " --privileged -sP "
  # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap 

