- platform: plex
- platform: cast
  host: 192.168.9.206
- platform: samsungtv
  host: 192.168.9.199
  port: 8001
  name: Living Room TV
  timeout: 1
- platform: apple_tv
  host: 192.168.9.242
  login_id: 00000000-3c11-5c07-c05e-49dd686541cb
