- platform: plex
- platform: cast
  host: 192.168.9.206

# - platform: samsungtv
#   host: 192.168.9.199
#   port: 8001
#   name: SamsungTV
#   # timeout: 1
#   mac: f8:77:b8:90:6e:5e

# - platform: apple_tv
#   host: 192.168.9.242
#   login_id: !secret apple_tv_login_id

- platform: mpd
  host: 192.168.9.79
  password: mpd
  port: 6600
