light:
  - platform: mqtt_json
    name: 'AiLight 299BEC'
    state_topic: '/AiLight/299BEC/state'
    command_topic: '/AiLight/299BEC/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: mqtt_json
    name: 'AiLight 29A0D5'
    state_topic: '/AiLight/29A0D5/state'
    command_topic: '/AiLight/29A0D5/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: mqtt_json
    name: 'AiLight 2550D0'
    state_topic: '/AiLight/2550D0/state'
    command_topic: '/AiLight/2550D0/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: mqtt_json
    name: 'AiLight 2553E5'
    state_topic: '/AiLight/2553E5/state'
    command_topic: '/AiLight/2553E5/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: mqtt_json
    name: 'AiLight 254EF3'
    state_topic: '/AiLight/254EF3/state'
    command_topic: '/AiLight/254EF3/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: mqtt_json
    name: 'AiLight 255346'
    state_topic: '/AiLight/255346/state'
    command_topic: '/AiLight/255346/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: mqtt_json
    name: 'AiLight 2F0349'
    state_topic: '/AiLight/2F0349/state'
    command_topic: '/AiLight/2F0349/set'
    color_temp: true
    brightness: true
    rgb: true
    white_value: true
    effect: false
    optimistic: false
  - platform: group
    name: living_room_fan
    entities:
      - light.ailight_2550D0
      - light.ailight_299BEC
      - light.ailight_254EF3
      - light.ailight_29A0D5


group:
  ailights:
    name: AiLights
    entities:
      - light.ailight_254EF3
      - light.ailight_2550D0
      - light.ailight_255346
      - light.ailight_2553E5
      - light.ailight_299BEC
      - light.ailight_29A0D5
      - light.ailight_2F0349
  #living_room_fan:
  #  name: Living Room Fan Lights
  #  entities:
  #    - light.ailight_2550D0
  #    - light.ailight_299BEC
  #    - light.ailight_254EF3
  #    - light.ailight_29A0D5
#  table_lights:
#    name: Table Lights
#    entities:
#      - light.ailight_255346
#      - light.ailight_2553E5

scene:
  - name: Living Worktime
    entities:
      light.living_room_fan:
        state: on
        brightness: 255
        white_value: 255
        rgb_color: [255,255,255]
  - name: Living Daytime
    entities:
      light.living_room_fan:
        state: on
        brightness: 255
        white_value: 0
        rgb_color: [255,240,100]
  - name: Living Nighttime
    entities:
      light.living_room_fan:
        state: on
        brightness: 128
        white_value: 0
        rgb_color: [255,240,100]
  - name: Living Party
    entities:
      light.ailight_254EF3:
        state: on
        brightness: 255
        white_value: 0
        rgb_color: [255,0,0]
      light.ailight_299BEC:
        state: on
        brightness: 255
        white_value: 0
        rgb_color: [255,0,0]
      light.ailight_2550D0:
        state: on
        brightness: 255
        white_value: 0
        rgb_color: [0,0,255]
      light.ailight_29A0D5:
        state: on
        brightness: 255
        white_value: 0
        rgb_color: [0,0,255]

homeassistant:
  customize:
    light.living_room_fan:
      friendly_name: 'Living Room Fan Lights'
      emulated_hue_hidden: false
      emulated_hue_name: "Living Room Lights"
#    group.table_lights:
#      emulated_hue_hidden: false
#      emulated_hue_name: "Table Lights"
    scene.living_daytime:
      emulated_hue_hidden: false
      emulated_hue_name: "Living Daytime"
    scene.living_nighttime:
      emulated_hue_hidden: false
      emulated_hue_name: "Living Nighttime"
    scene.living_party:
      emulated_hue_hidden: false
      emulated_hue_name: "Party Time"
    scene.living_worktime:
      emulated_hue_hidden: false
      emulated_hue_name: "Living Worktime"
    light.ailight_255346:
      friendly_name: "Bedside"
    light.ailight_2553e5:
      friendly_name: "Porch Table"
      
