switch:
  - platform: mqtt
    name: "SLAMPHER_173A91"
    state_topic: "/espurna/switch/SLAMPHER_173A91/relay/0/get"
    command_topic: "/espurna/switch/SLAMPHER_173A91/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "SLAMPHER_173B67"
    state_topic: "/espurna/switch/SLAMPHER_173B67/relay/0/get"
    command_topic: "/espurna/switch/SLAMPHER_173B67/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "SLAMPHER_1735B9"
    state_topic: "/espurna/switch/SLAMPHER_1735B9/relay/0/get"
    command_topic: "/espurna/switch/SLAMPHER_1735B9/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "ECOPLUG_07780E"
    state_topic: "/espurna/switch/ECOPLUG_07780E/relay/0/get"
    command_topic: "/espurna/switch/ECOPLUG_07780E/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "ECOPLUG_024662"
    state_topic: "/espurna/switch/ECOPLUG_024662/relay/0/get"
    command_topic: "/espurna/switch/ECOPLUG_024662/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true

light:
  - platform: mqtt
    name: "AILIGHT_299BEC"
    state_topic: "/espurna/switch/AILIGHT_299BEC/relay/0/get"
    command_topic: "/espurna/switch/AILIGHT_299BEC/relay/0/set"
    rgb_state_topic: "/espurna/switch/AILIGHT_299BEC/color/get"
    rgb_command_topic: "/espurna/switch/AILIGHT_299BEC/color/set"
    qos: 0
    payload_on: 1
    payload_off: 0
    optimistic: false

homeassistant:
  customize:
    switch.slampher_1735b9:
      friendly_name: Porch Right Light
    switch.slampher_173a91:
      friendly_name: Porch Left Light
    switch.slampher_173b67:
      friendly_name: Side Door Light
      emulated_hue: true
      emulated_hue_name: "Side Light"
    group.porch_lights:
      emulated_hue: true
      emulated_hue_name: "Porch Lights"

group:
  porch_lights:
    name: Porch Lights
    entities:
      - switch.slampher_1735b9
      - switch.slampher_173a91
