switch:
  - platform: mqtt
    name: "SLAMPHER_173A91"
    state_topic: "/espurna/switch/SLAMPHER173A91/relay/0"
    command_topic: "/espurna/switch/SLAMPHER173A91/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "SLAMPHER_173B67"
    state_topic: "/espurna/switch/SLAMPHER173B67/relay/0"
    command_topic: "/espurna/switch/SLAMPHER173B67/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "SLAMPHER_1735B9"
    state_topic: "/espurna/switch/SLAMPHER1735B9/relay/0"
    command_topic: "/espurna/switch/SLAMPHER1735B9/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "ECOPLUG_07780E"
    state_topic: "/espurna/switch/ECOPLUG07780E/relay/0"
    command_topic: "/espurna/switch/ECOPLUG07780E/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "ECOPLUG_024662"
    state_topic: "/espurna/switch/ECOPLUG024662/relay/0"
    command_topic: "/espurna/switch/ECOPLUG024662/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
  - name: ECOPLUG04E301
    platform: mqtt
    state_topic: espurna/ECOPLUG04E301/relay/0
    command_topic: espurna/ECOPLUG04E301/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: espurna/ECOPLUG04E301/status
    payload_available: 1
    payload_not_available: 0

homeassistant:
  customize:
    switch.slampher_1735b9:
      friendly_name: Porch Right Light
    switch.slampher_173a91:
      friendly_name: Porch Left Light
    switch.slampher_173b67:
      friendly_name: Side Door Light
      emulated_hue_hidden: false
      emulated_hue_name: "Side Porch Light"
    group.porch_lights:
      emulated_hue_hidden: false
      emulated_hue_name: "Front Porch Lights"
    switch.ecoplug04e301:
      friendly_name: Bush Lights
      emulated_hue_hidden: false
      emulated_hue_name: "Bush Lights"

group:
  porch_lights:
    name: Porch Lights
    entities:
      - switch.slampher_1735b9
      - switch.slampher_173a91
