sensor:
#  - platform: rest
#    resource: http://ip.jsontest.com
#    resource: http://diagnostic.opendns.com/myip
#    name: external_ip
#    value_template: '{{ value_json.ip }}'
  - platform: command_line
    name: external_ip
    command: /usr/bin/curl -sf http://diagnostic.opendns.com/myip | /usr/bin/head -n1
    scan_interval: 1800


automation:
  - alias: Notify New External IP
    trigger:
      platform: state
      entity_id: sensor.external_ip
    condition:
      - condition: template
        value_template: >
          {% if trigger is defined %}
            {{ trigger.to_state.state != "unknown" }}
          {% else %}
            true
          {% endif %}
    action:
      - service: notify.pushbullet
        data:
          title: Home Assistant IP
          message: External IP changed to {{ states.sensor.external_ip.state }}.
