automation:
  - alias: ios_tree_notification
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: notify.ios_dwmi5
        data:
          title: "Test title"
          message: "Test message"
          data:
            push:
              badge: 0
              category: "TREE"
            action_data:
              entity_id: switch.christmas_tree
              my_custom_data: foo_bar

  - alias: IOS Test On
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TREE_ON
    action:
      - service: homeassistant.turn_on
        entity_id: switch.christmas_tree

  - alias: IOS Test Off
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TREE_OFF
    action:
      - service: homeassistant.turn_off
        entity_id: switch.christmas_tree
