homeassistant:
  customize:
    device_tracker.chromecast:
      hidden: true
    device_tracker.engenius_ap:
      hidden: true
    device_tracker.viostor:
      hidden: true
    device_tracker.sonicwall:
      hidden: true
    device_tracker.airport_extreme:
      hidden: true
    device_tracker.ecoplug_2:
      hidden: true
    device_tracker.appletv:
      hidden: true
    device_tracker.hpmini:
      hidden: true
    device_tracker.samsungtv:
      hidden: true
    device_tracker.yeelight1:
      hidden: true

    device_tracker.5ccf7f29a0d5:
      hidden: true
    device_tracker.7cc7090fefcb:
      hidden: true
    device_tracker.b827eb480cb2:
      hidden: true


sensor:
  - platform: template
    sensors:
        chromecast:
          friendly_name: 'ChromeCast'
          value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'Offline' }}"
        engenius_ap:
          friendly_name: 'EnGenius AP'
          value_template: "{{ 'Online' if is_state('device_tracker.engenius_ap', 'home') else 'Offline' }}"
        viostor_nvr:
          friendly_name: 'VioStor NVR'
          value_template: "{{ 'Online' if is_state('device_tracker.viostor', 'home') else 'Offline' }}"
        sonicwall:
          friendly_name: 'SonicWall'
          value_template: "{{ 'Online' if is_state('device_tracker.sonicwall', 'home') else 'Offline' }}"
        airport_extreme:
          friendly_name: 'Airport Extreme'
          value_template: "{{ 'Online' if is_state('device_tracker.airport_extreme', 'home') else 'Offline' }}"
        ecoplug_2:
          friendly_name: 'ecoPlug 2'
          value_template: "{{ 'Online' if is_state('device_tracker.ecoplug_2', 'home') else 'Offline' }}"
        hpmini:
          friendly_name: 'HP mini'
          value_template: "{{ 'Online' if is_state('device_tracker.hpmini', 'home') else 'Offline' }}"
        yeelight1:
          friendly_name: 'YeeLight 1'
          value_template: "{{ 'Online' if is_state('device_tracker.yeelight1', 'home') else 'Offline' }}"
        appletv:
          friendly_name: 'Apple TV'
          value_template: "{{ 'Online' if is_state('device_tracker.appletv', 'home') else 'Offline' }}"

group:
  network_devices:
    name: Network Devices
    entities:
      - sensor.sonicwall
      - sensor.engenius_ap
      - sensor.airport_extreme
      - sensor.viostor_nvr
      - sensor.hpmini
      - sensor.ecoplug_2
      - sensor.chromecast
      - sensor.yeelight1
      - sensor.appletv
