group:
  kitchen:
    name: Kitchen
    control: hidden
    entities:
      - binary_sensor.kitchen_52_20
      - sensor.kitchen_52_10
      - sensor.kitchen_52_11
      - sensor.kitchen_52_15
      - light.kitchen_52_33
  #    - switch.kitchen_52_21
      - light.nook_light

input_boolean:
  kitchen_strip:

homeassistant:
  customize:
    input_boolean.kitchen_strip:
      hidden: true
      emulated_hue: true
      emulated_hue_name: Kitchen Light

script:
  kitchen_lights_motion:
    alias: "Kitchen Motion"
    sequence:
      - service: script.turn_off
        data:
          entity_id: script.kitchen_lights_motion_off
      - service: light.turn_on
        data:
          entity_id: light.kitchen_52_33
          rgb_color: [16, 0, 0]
          brightness: 32
      - service: script.turn_on
        data:
          entity_id: script.kitchen_lights_motion_off

  kitchen_lights_motion_off:
    alias: "Kitchen Motion Off"
    sequence:
      - delay:
          minutes: 1
      - service: light.turn_off
        data:
          entity_id: light.kitchen_52_33

automation:
  - alias: Kitchen Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_52_20
        to: 'on'
    condition:
      condition: numeric_state
      entity_id: sensor.kitchen_52_15
      below: 30
    action:
      service: homeassistant.turn_on
      entity_id: script.kitchen_lights_motion

  - alias: Kitchen Button
    trigger:
      - platform: state
        entity_id: switch.kitchen_52_21
        to: 'on'
    action:
      service: light.toggle
      entity_id: light.kitchen_52_33

  - alias: Kitchen Strip Scene On
    trigger:
      - platform: state
        entity_id: input_boolean.kitchen_strip
        to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: scene.kitchen_bright_white
  - alias: Motion Alarm Disarm
    trigger:
      - platform: state
        entity_id: input_boolean.kitchen_strip
        to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: light.kitchen_52_33
