script:
  living_room_toggle:
    alias: Living Room Toggle
    sequence:
      - service: script.turn_on
        data:
          entity_id: 'script.living_room_toggle_1'
      - service: script.turn_on
        data:
          entity_id: 'script.living_room_toggle_2'


  living_room_toggle_1:
    sequence:
      - condition: state
        entity_id: 'group.living_room_fan'
        state: 'on'
      - service: homeassistant.turn_off
        data:
          entity_id: group.living_room_fan

  living_room_toggle_2:
    sequence:
      - condition: state
        entity_id: 'group.living_room_fan'
        state: 'off'
      - service: scene.turn_on
        data:
          entity_id: 'scene.living_nighttime'

group:
  livingroom:
    name: Living Room
    control: hidden
    entities:
      - binary_sensor.living_room_51_20
      - sensor.living_last_motion
      - sensor.living_room_51_10
      - sensor.living_room_51_11
      - sensor.living_room_51_15
      - light.living_room_51_30
      - switch.christmas_tree
      - switch.samsungtv
      - switch.fairy_bottle
      - group.living_room_fan
      - scene.living_daytime
      - scene.living_nighttime
      - scene.living_party
      - scene.living_worktime

sensor:
  - platform: template
    sensors:
      living_last_motion:
        value_template: '{% if states.automation.living_motion and states.automation.living_motion.attributes.last_triggered %}
                           {{ as_timestamp(states.automation.living_motion.attributes.last_triggered) | timestamp_custom("%b %d %X") }}
                         {% else %}
                           Never
                         {% endif %}'
        friendly_name: Last Motion


automation:
  - alias: Living Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_51_20
        to: 'on'
    action:
