input_boolean:
  motion_alarm:
    name: Motion Alarm
    icon: mdi:alarm-multiple
    initial: off
  motion_alarm_delay:
    initial: off


homeassistant:
  customize:
    input_boolean.motion_alarm_delay:
      hidden: true
      emulated_hue: true
      emulated_hue_name: Motion Detection


automation:
  - alias: Motion Alarm Notification
    trigger:
  #    - platform: state
  #      entity_id: binary_sensor.garage_motion
  #      from: 'off'
  #      to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_51_20
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_52_20
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bedroom_53_20
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.porch_54_20
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.motion_alarm
        state: 'on'
    action:
      - service: notify.pushbullet
        data_template:
          message: >
            Motion detected: {{ trigger.to_state.entity_id|default("Unknown") }}
      - service: light.turn_on
        data:
          entity_id: light.nook_light
          effect: "Strobe epilepsy!"
      - service: notify.ios_dwmi5
        data:
          title: "Motion title"
          message: "Motion detected"
          data:
            push:
              badge: 1
              sound: "US-EN-Alexa-Motion-Detected-Generic.wav"
              category: "ALARM"
            action_data:
              entity_id: switch.christmas_tree
              my_custom_data: foo_bar

  - alias: Motion Alarm Flash
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM
    action:
      - service: homeassistant.turn_on
        entity_id: script.motion_alarm_flash

  - alias: Cancel the alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SILENCE_ALARM
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.motion_alarm


  - alias: Motion Alarm Arm
    trigger:
      - platform: state
        entity_id: input_boolean.motion_alarm_delay
        to: 'on'
    action:
      - delay: 3:00
      - service: homeassistant.turn_on
        entity_id: input_boolean.motion_alarm
        
  - alias: Motion Alarm Disarm
    trigger:
      - platform: state
        entity_id: input_boolean.motion_alarm_delay
        to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.motion_alarm

script:
  motion_alarm_flash:
    sequence:
      - service: light.turn_on
        data:
          entity_id: group.living_room_fan
          flash: long
          rgb_color: [255,0,0]
          white_value: 0
          brightness: 255
