input_boolean:
  motion_alarm:
    name: Motion Alarm
    icon: mdi:alarm-multiple
    initial: off
  motion_alarm_delay:
    initial: off


homeassistant:
  customize:
    input_boolean.motion_alarm_delay:
      hidden: true
      emulated_hue: true
      emulated_hue_name: Motion Detection


automation:
  - alias: Motion Alarm Notification
    trigger:
  #    - platform: state
  #      entity_id: binary_sensor.garage_motion
  #      from: 'off'
  #      to: 'on'
      - platform: state
        entity_id: binary_sensor.living_room_51_20
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_52_20
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bedroom_53_20
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.porch_54_20
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.motion_alarm
        state: 'on'
    action:
      - service: notify.pushbullet
        data_template:
          message: >
            Motion detected: {{ trigger.to_state.entity_id }}
      - service: notify.ios_dwmi5
        data:
          message: "Motion at home!"
          data:
            push:
              badge: 1
              sound: "US-EN-Alexa-Motion-Detected-Generic.wav"
              category: 'ALARM'
            

  - alias: Motion Alarm Arm
    trigger:
      - platform: state
        entity_id: input_boolean.motion_alarm_delay
        to: 'on'
    action:
      - delay: 3:00
      - service: homeassistant.turn_on
        entity_id: input_boolean.motion_alarm
  - alias: Motion Alarm Disarm
    trigger:
      - platform: state
        entity_id: input_boolean.motion_alarm_delay
        to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.motion_alarm
