group:
  porch:
    name: Porch
    control: hidden
    entities:
      - binary_sensor.porch_54_20
      - sensor.porch_last_motion
      - sensor.porch_54_10
      - sensor.porch_54_11
      - sensor.porch_54_15
  #    - light.porch_54_33
  #    - switch.porch_54_21
      - input_select.porch_led_effect
#      - input_slider.porch_animation_speed
      - input_number.porch_animation_speed
      - light.porch_leds



light:
  - platform: mqtt
    name: "Porch LEDs"
    command_topic: "bruh/mqttstrip/setpower"
    state_topic: "bruh/mqttstrip/setpowerpub"
    rgb_state_topic: "bruh/mqttstrip/setcolorpub"
    rgb_command_topic: "bruh/mqttstrip/setcolor"
    brightness_state_topic: "bruh/mqttstrip/setbrightnesspub"
    brightness_command_topic: "bruh/mqttstrip/setbrightness"
    optimistic: false

input_select:
  porch_led_effect:
    name: Porch LED Effect
    options:
     - "BPM"
     - "Candy Cane"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Noise"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"

input_number:
  porch_animation_speed:
    name: Bruh Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation:
  - alias: "Porch Input Effect"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.porch_led_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "Porch Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_slider.porch_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'

  - alias: Porch Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.porch_54_20
        to: 'on'
    action:


sensor:
  - platform: template
    sensors:
      porch_last_motion:
        value_template: '{% if states.automation.porch_motion and states.automation.porch_motion.attributes.last_triggered %}
                           {{ as_timestamp(states.automation.porch_motion.attributes.last_triggered) | timestamp_custom("%b %d %X") }}
                         {% else %}
                           Never
                         {% endif %}'
        friendly_name: Last Motion

scene:
 - name: Blue Porch
   entities:
     light.porch_leds:
       state: on
       rgb_color: [ 0, 0, 255 ]
       brightness: 255


homeassistant:
  customize:
    scene.blue_porch:
      emulated_hue_hidden: false
      emulated_hue_name: Blue Porch
