group:
  raspi:
    name: Raspberry Pi
    icon: mdi:raspberrypi
    entities:
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.swap_use_percent
      - sensor.disk_free_
      - sensor.last_boot
      - sensor.cpu_temperature
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
 

sensor:
  - platform: dht
    sensor: DHT11
    pin: 22
    monitored_conditions:
      - temperature
      - humidity

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value|int // 1000 }}'

  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: last_boot
      - type: load_1m
      - type: load_5m
      - type: load_15m

binary_sensor:
  - platform: rpi_gpio
    pull_mode: "DOWN"
    bouncetime: 50
    invert_logic: false
    ports:
      27: 'Garage Motion'

cover:
  - platform: rpi_gpio
    relay_time: 1.0
    state_pull_mode: 'DOWN'
    invert_logic: false
    covers:
      - relay_pin: 23
        state_pin: 18
        name: 'Garage Door'

switch:
  - platform: rpi_gpio
    invert_logic: true
    # GPIO numbers
    ports:
      24: 'Garage Relay'
