sensor:
  - platform: template
    sensors:
      sunrise:
        entity_id: sun.sun
        value_template: "{% if states.sun.sun and states.sun.sun.attributes.next_rising %}
                           {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M', True) }}
                         {% else %}
                           Never
                         {% endif %}"
      sunset:
        entity_id: sun.sun
        value_template: "{% if states.sun.sun and states.sun.sun.attributes.next_setting %}
                           {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M', True) }}
                         {% else %}
                           Never
                         {% endif %}"


homeassistant:
  customize:
    sensor.sunrise:
      friendly_name: Next Sunrise
    sensor.sunset:
      friendly_name: Next Sunset
