automation:
  - alias: Side Light upon arrival
    trigger:
      - platform: state
        entity_id: device_tracker.toyota_prius, device_tracker.owntracks_dwmi8, device_tracker.jennifer_wilsons_iphone
        to: home
    condition:
      - condition: template
        value_template: '{{ states.sun.sun.attributes.elevation < 4 }}'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.slampher_173b67
      - service: notify.pushbullet
        data_template:
          title: "Welcome home {{ trigger.entity_id }}!"
          message: "{{ trigger.entity_id }} arrived home at {{ now() }} to a lit side light."
      - delay: 10:00
      - service: homeassistant.turn_off
        entity_id: switch.slampher_173b67

  - alias: Update Phone Location when Prius parks
    trigger:
      - platform: state
        entity_id: device_tracker.toyota_prius
    action:
      - service: notify.ios_dwmi8
        data:
          message: "request_location_update"
