sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    units: us
    monitored_conditions:
      - summary
      # - icon
      # - nearest_storm_distance
      # - nearest_storm_bearing
      # - precip_type
      # - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      # - dew_point
      - wind_speed
      # - wind_bearing
      # - cloud_cover
      - humidity
      # - pressure
      # - visibility
      # - ozone
      - minutely_summary
      - hourly_summary
      # - daily_summary
      # - temperature_max
      # - temperature_min
      # - apparent_temperature_max
      # - apparent_temperature_min
      # - precip_intensity_max

camera:
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=DOX&brand=wui&num=1&delay=100&type=NTP&frame=0&scale=1&noclutter=1&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=0&severe=0&rainsnow=1&lightning=1&smooth=1&rand=24427697&lat=38.85&lon=-75.44&label=you
    name: Delaware Radar
  - platform: generic
    still_image_url: http://images.intellicast.com/WxImages/RadarLoop/shd_None_anim.gif
    name: Animated Radar

homeassistant:
  customize:
    sensor.dark_sky_apparent_temperature:
      friendly_name: Outside Feels Like
    sensor.dark_sky_humidity:
      friendly_name: Outdoor Humidity
      icon: mdi:water-percent
    sensor.dark_sky_temperature:
      friendly_name: Outdoor Temp
    sensor.dark_sky_summary:
      friendly_name: Summary
      icon: mdi:weather-cloudy
    sensor.dark_sky_daily_high_temperature:
      friendly_name: High Temp
    sensor.dark_sky_daily_low_temperature:
      friendly_name: Low Temp
    sensor.dark_sky_minutely_summary:
      friendly_name: Hourly
    sensor.dark_sky_hourly_summary:
      friendly_name: Forecast
    sensor.dark_sky_wind_speed:
      friendly_name: Wind Speed
    sensor.dark_sky_precip_probability:
      friendly_name: Precipitation

