light:
  platform: yeelight
  devices:
    192.168.9.237:
      name: Nook Light
      transition: 1000
      save_on_change: true

homeassistant:
  customize:
    light.nook_light:
      friendly_name: Kitchen Nook Light
      emulated_hue: true
      emulated_hue_name: "Nook Light"
