input_boolean:
  zone_alert:
    name: Zone Change Alert
    icon: mdi:alarm-multiple
    initial: off

automation:
  - alias: Zone Change Alert
    trigger:
      platform: state
      entity_id: device_tracker.owntracks_dwmi5
    condition:
      condition: state
      entity_id: input_boolean.zone_alert
      state: 'on'
    action:
      service: notify.pushbullet
      data:
        title: Home Assistant Zone
        message: Zone changed to {{ states.device_tracker.owntracks_dwmi5.state }}.
